### ISSUE TITLE
WES - Sorting in Moka

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#276] opened 2018-08-29 06:53 UTC
Hi,

Would it be possible to re-enable variant sorting by gene and panel name in Moka please?

Thanks,
Heidi

**Comment by aledj2** [comment] 2018-08-29 13:05
Hi Heidi,

Sue also raised this a while ago (#257 ). We're looking into it and not sure why we can't do that sorting anymore. Can you sort variants on the just panel name alone?

**Comment by hkuoppamaa** [comment] 2018-08-29 14:49
Hi Aled,

Nope, sorting by panel name alone doesn't work either.

**Comment by andyb3** [comment] 2018-11-22 12:16
Duplicate of https://github.com/moka-guys/helpdesk/issues/257

**Closed by andyb3** 2018-11-22 12:16 UTC
